### ISSUE TITLE
"Failed to generate cache, does your model exist?" error

### ISSUE THREAD

**Issue by xandermcg** [kanjieater/anki-plugin-heisigs-rtk#1]
Hi,
I get the error mentioned in the title when opening the browser in Anki. Plus the _"Bulk-add RTK Keywords"_ option never shows up.
I've tried changing the necessary variables in 'rtkkw.pw' as instructed, I also tried using the premade deck you've supplied and made sure the note type is correct. I'm stuck now, would love to be able to make use of this addon if you can help me out! Thanks

**Comment by kanjieater** [comment]
The docs have been updated to address this. Sorry for the delay. For further support please ask on discord.

https://github.com/kanjieater/anki-plugin-heisigs-rtk#failed-to-generate-cache-does-your-model-exist-error
